[package]
name = "eth-keygen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
ctrlc = "3.4.5"
hex = "0.4.3"
k256 = "0.13.4"
num_cpus = "1.16.0"
rand = "0.8.5"
sha3 = "0.10.8"
